#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hello:
    path: /hello
    controller: App\Controller\WorkshopPhp::hello

product:
    path: /product
    controller: App\Controller\ProductController::createProduct

